name:                15puzzle
version:             0.1.0.0
github:              "alexunxus/PFP_final_project"
license:             BSD3
author:              "Kuan-Yao Huang, Aditya Sidharta"
maintainer:          "aditya.sdrt@gmail.com"
copyright:           "2021 - Kuan-Yao Huang, Aditya Sidharta"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alexunxus/PFP_final_project#readme>

dependencies:
- base >= 4.7 && < 5
- PSQueue
- tasty
- tasty-hunit
- random-shuffle
- random

library:
  source-dirs: src

executables:
  15puzzle-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 15puzzle
    - PSQueue

  15puzzle-generate:
    main:                GenFile.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 15puzzle
    - random-shuffle
    - random

tests:
  15puzzle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 15puzzle
    - PSQueue
    - tasty
    - tasty-hunit
    - random-shuffle
    - random